# Uncomment the next line to define a global platform for your project

platform :ios, '13.0'

target 'DyteiOSUIKitExample' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    # Pods for DyteiOSUIKitExample
    pod 'DyteUiKit' , '0.2.0'
end




